Feature/button component
isdi-coders-2023/coding-adventure-Roman-Demchuk-front-202301-BCN pull request #1
Opened 2023-02-27 16:12 UTC by rom-dem

Hello, ya está lista la primera fase del proyecto. Revisalo, por favors.

2023-02-27 16:21 UTC, MMLORENA requested changes

2023-02-27 16:21 UTC, catatarelli requested changes

2023-02-27 16:21 UTC, MMLORENA commented on package.json
> +    "test:dev": "react-scripts test --watchAll",
En react no necesitas este script

2023-02-27 16:21 UTC, catatarelli commented on src/component/Button/Button.test.tsx
> +  describe("When rendered", () => {
When rendered sin mas?

2023-02-27 16:21 UTC, catatarelli commented on src/component/Button/Button.test.tsx
> +      const expectedButtonTex = "Raúuuul";
Tex?

2023-02-27 16:21 UTC, MMLORENA commented on src/GlobalStyles.tsx
> +        font-family: "Roboto", sans-serif;
Utiliza variables de css o el theme provider para no repetir fuentes y colores

2023-02-27 16:21 UTC, catatarelli commented on src/component/Button/Button.test.tsx
> +      const result = screen.getByRole("button", { name: expectedButtonTex });
result? que te devuelve mas especificamente?

2023-02-27 16:21 UTC, catatarelli commented on src/component/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
podemos sacar los colores a variables o Theme Provider?

2023-02-27 17:06 UTC, MMLORENA requested changes

2023-02-27 17:06 UTC, MMLORENA commented on src/GlobalStyles.tsx
> +    --titleFont: "Outfit", sans-serif;
Esta no es la fuente de los headings

2023-02-28 14:16 UTC, rom-dem commented on src/GlobalStyles.tsx
> +    --titleFont: "Outfit", sans-serif;
La he quitado de momento.

2023-02-28 14:42 UTC, mariogl approved these changes

2023-02-28 14:50 UTC, catatarelli approved these changes

2023-02-28 14:51 UTC, rom-dem commented on src/GlobalStyles.tsx
> +        color: #fff
vale. a mi me sonaba que el blanco lo ponemos a chapa. peeero, tienes razón. lo voy a poner.

2023-02-28 14:51 UTC, merged